/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function DeviceCount({ count }) {
  return (
    <DeviceWrapper>
      <DeviceLabel>モバイル/PC 合計</DeviceLabel>
      <CountDisplay>
        <Count>{count}</Count>
        <Unit>台</Unit>
      </CountDisplay>
    </DeviceWrapper>
  );
}

const DeviceWrapper = styled.div`
  align-self: center;
  display: flex;
  gap: 6px;
`;

const DeviceLabel = styled.p`
  align-self: start;
  margin-top: 11px;
  flex-grow: 1;
  font: 11px Arial, sans-serif;
`;

const CountDisplay = styled.div`
  display: flex;
  gap: 2px;
  white-space: nowrap;
`;

const Count = styled.span`
  font: 28px Arial, sans-serif;
`;

const Unit = styled.span`
  align-self: start;
  margin-top: 10px;
  font: 11px Arial, sans-serif;
`;

export default DeviceCount;
