/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import DeviceCount from "./DeviceCount";
import PriceInfo from "./PriceInfo";

function PricingDisplay() {
  return (
    <PricingCard>
      <PricingContent>
        <DeviceCount count={1} />
        <PriceInfo price={220} />
      </PricingContent>
    </PricingCard>
  );
}

const PricingCard = styled.section`
  display: flex;
  max-width: 225px;
  flex-direction: column;
  color: #fff;
  font-weight: 700;
  text-align: center;
  justify-content: center;
`;

const PricingContent = styled.div`
  border-radius: 4px;
  background-color: #66b574;
  display: flex;
  width: 100%;
  flex-direction: column;
  padding: 9px 36px 0;
  border: 1px solid #66b574;
`;

export default PricingDisplay;
