/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function PriceInfo({ price }) {
  return <PriceWrapper>月額利用登録 {price}円 (税込)</PriceWrapper>;
}

const PriceWrapper = styled.p`
  padding: 10px;
  font: 11px Arial, sans-serif;
`;

export default PriceInfo;
