/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

const featuresData = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/d3933300b436708fba79c2d6b5a3c0cf471809948d2a9a00c1a439b3cfd3b5f0?apiKey=3041bfe48db34fff9838d53ac5a71114&&apiKey=3041bfe48db34fff9838d53ac5a71114",
    title: "広告ブロッカー",
    description:
      "AdGuardは迷惑なバナー、ポップアップ、ビデオ広告を一括で処理します。",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/732572a44ca49a20ec3dc2605cf579983bbfafa85b60407ea250b8dff19aef4e?apiKey=3041bfe48db34fff9838d53ac5a71114&&apiKey=3041bfe48db34fff9838d53ac5a71114",
    title: "プライバシー保護",
    description:
      "AdGuardは、ウェブに存在する多数のトラッカーやアクティビティアナライザーからデータを保護します。",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e55eae0de72f328bf4a6c6504924d5f3e833a16bc2e126512ec6979ab1c655ec?apiKey=3041bfe48db34fff9838d53ac5a71114&&apiKey=3041bfe48db34fff9838d53ac5a71114",
    title: "ブラウジングセキュリティ",
    description:
      "AdGuardをインストールすれば、不正なウェブサイトやマルウェアからの攻撃を避けることができます。",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7368f32ce74d9f7735daa2b5df35359e9685d804de1f38601b0a35a6023e8206?apiKey=3041bfe48db34fff9838d53ac5a71114&&apiKey=3041bfe48db34fff9838d53ac5a71114",
    title: "ペアレンタルコントロール",
    description:
      "お子様が不適切なコンテンツやアダルトコンテンツにアクセスすることを制限できます。",
  },
];

function Features() {
  return (
    <FeaturesWrapper>
      <FeaturesContainer>
        {featuresData.map((feature, index) => (
          <FeatureColumn key={index}>
            <FeatureIcon
              loading="lazy"
              src={feature.icon}
              alt={feature.title}
            />
            <FeatureTitle>{feature.title}</FeatureTitle>
            <FeatureDescription>{feature.description}</FeatureDescription>
          </FeatureColumn>
        ))}
      </FeaturesContainer>
    </FeaturesWrapper>
  );
}

const FeaturesWrapper = styled.section`
  background-color: #d8d8d8;
  align-self: stretch;
  display: flex;
  width: 100%;
  align-items: center;
  justify-content: center;
  padding: 31px 60px;
  @media (max-width: 991px) {
    padding: 31px 20px;
  }
`;

const FeaturesContainer = styled.div`
  display: flex;
  width: 100%;
  max-width: 1182px;
  justify-content: space-between;
  @media (max-width: 991px) {
    flex-direction: column;
    align-items: center;
  }
`;

const FeatureColumn = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  color: #4a4a4a;
  width: 25%;
  @media (max-width: 991px) {
    width: 100%;
    margin-top: 40px;
  }
`;

const FeatureIcon = styled.img`
  width: 126px;
  height: 126px;
  object-fit: contain;
`;

const FeatureTitle = styled.h3`
  text-align: center;
  margin-top: 19px;
  font: 700 17px Arial, sans-serif;
`;

const FeatureDescription = styled.p`
  text-align: center;
  margin-top: 20px;
  font: 400 14px/20px Arial, sans-serif;
`;

export default Features;
