/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

const plans = [
  { devices: 1, price: 220 },
  { devices: 3, price: 330 },
  { devices: 6, price: 550 },
];

function PricingPlans() {
  return (
    <PlansContainer>
      {plans.map((plan, index) => (
        <PlanButton key={index}>
          <PlanDetails>
            <PlanLabel>モバイル/PC 合計</PlanLabel>
            <DeviceCount>
              <DeviceNumber>{plan.devices}</DeviceNumber>
              <DeviceUnit>台</DeviceUnit>
            </DeviceCount>
          </PlanDetails>
          <PlanPrice>月額利用登録 {plan.price}円 (税込)</PlanPrice>
        </PlanButton>
      ))}
    </PlansContainer>
  );
}

const PlansContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 10px;
  margin-top: 37px;
`;

const PlanButton = styled.button`
  border-radius: 4px;
  background-color: #66b574;
  display: flex;
  width: 225px;
  max-width: 100%;
  flex-direction: column;
  color: #fff;
  font-weight: 700;
  text-align: center;
  padding: 9px 36px 0;
  border: 1px solid #66b574;
  cursor: pointer;
  @media (max-width: 991px) {
    padding: 9px 20px 0;
  }
`;

const PlanDetails = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
`;

const PlanLabel = styled.span`
  font: 11px Arial, sans-serif;
`;

const DeviceCount = styled.div`
  display: flex;
  align-items: baseline;
`;

const DeviceNumber = styled.span`
  font: 28px Arial, sans-serif;
`;

const DeviceUnit = styled.span`
  font: 11px Arial, sans-serif;
  margin-left: 2px;
`;

const PlanPrice = styled.div`
  padding: 10px;
  font: 11px Arial, sans-serif;
`;

export default PricingPlans;
